# Generated by Django 3.1.2 on 2020-11-01 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ans',
            fields=[
                ('anum', models.AutoField(primary_key=True, serialize=False)),
                ('atext', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False)),
                ('mname', models.CharField(db_index=True, max_length=15)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('pw', models.CharField(db_index=True, max_length=16)),
                ('mphone', models.IntegerField(db_index=True, max_length=11)),
                ('email', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('snum', models.AutoField(primary_key=True, serialize=False)),
                ('sname', models.CharField(db_index=True, max_length=100)),
                ('sphone', models.IntegerField(db_index=True, max_length=11)),
                ('address', models.TextField(db_index=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=11)),
                ('category', models.CharField(db_index=True, max_length=200)),
                ('time', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('img', models.ImageField(upload_to='')),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('vnum', models.AutoField(primary_key=True, serialize=False)),
                ('vtext', models.TextField()),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='today.member')),
                ('snum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='today.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Res',
            fields=[
                ('rnum', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('rprice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='today.member')),
                ('snum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='today.studio')),
            ],
        ),
        migrations.CreateModel(
            name='Qna',
            fields=[
                ('qnum', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(allow_unicode=True, max_length=200, unique=True)),
                ('qpw', models.CharField(db_index=True, max_length=16)),
                ('qimg', models.ImageField(upload_to='')),
                ('title', models.TextField()),
                ('qtext', models.TextField()),
                ('id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='today.studio')),
            ],
        ),
    ]
