# Generated by Django 3.1.2 on 2020-11-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0002_auto_20201108_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Studio',
        ),
    ]
