# Generated by Django 3.1.2 on 2020-11-10 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0003_auto_20201110_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='studios', to='today.category'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='image',
            field=models.ImageField(blank=True, upload_to='studios/%Y/%m/%d'),
        ),
    ]
