# Generated by Django 3.1.2 on 2020-11-19 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('today', '0006_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='studio_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
