# Generated by Django 3.1.2 on 2020-11-19 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0008_auto_20201119_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_review', to='today.product'),
        ),
    ]
