# Generated by Django 3.1.2 on 2020-11-19 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0009_auto_20201119_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='author',
            new_name='review_author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='name',
            new_name='studio_name',
        ),
    ]
