# Generated by Django 3.1.2 on 2020-11-19 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0010_auto_20201119_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='studio_name',
        ),
    ]
