# Generated by Django 3.1.2 on 2020-11-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0011_remove_review_studio_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
