# Generated by Django 3.1.2 on 2020-11-19 04:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0013_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='name',
        ),
    ]
