# Generated by Django 3.1.2 on 2020-11-19 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('today', '0018_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='r_author',
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL),
        ),
    ]
