# Generated by Django 3.1.2 on 2020-11-19 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0019_auto_20201119_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
