# Generated by Django 3.1.2 on 2020-11-19 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0021_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
