# Generated by Django 3.1.2 on 2020-11-20 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0023_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='r_author',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='r_name',
            new_name='studio',
        ),
    ]
