# Generated by Django 3.1.2 on 2020-11-21 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('today', '0029_reservationdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReservationDate',
        ),
    ]
