# Generated by Django 3.1.2 on 2020-11-21 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('today', '0030_delete_reservationdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('sur_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('mobil_phone', models.IntegerField()),
                ('reservation_code', models.CharField(max_length=10)),
                ('date_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationDate',
            fields=[
                ('day_id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('T10_11', models.TextField(default='open')),
                ('T11_12', models.TextField(default='open')),
                ('T12_13', models.TextField(default='open')),
                ('T13_14', models.TextField(default='open')),
                ('T14_15', models.TextField(default='open')),
                ('T15_16', models.TextField(default='open')),
                ('T16_17', models.TextField(default='open')),
                ('T17_18', models.TextField(default='open')),
                ('T18_19', models.TextField(default='open')),
                ('T19_20', models.TextField(default='open')),
                ('T20_21', models.TextField(default='open')),
                ('r_studio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_studio', to='today.product')),
                ('r_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
