# Generated by Django 3.1.2 on 2020-11-15 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20201115_1717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='photo',
        ),
    ]
